name: Continuous Integration

on: [push, pull_request]

jobs:
  openjdk21:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Build project
        run: sbt test

      - name: Check Formatting
        run: sbt scalafmtCheckAll
